[package]
name = "rust_practice"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.74"
quote = "1.0.35"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
